// Carry the existing translations onto freshly split batches, apply the new
// release's translations, and write the `it/` files.
//
// The batches are regenerated by split.mjs whenever the shipped dictionaries change,
// so file names shift; the translations themselves must not. They are therefore
// re-attached by namespace and key, which is what they are actually about, and every
// key the release adds comes from the update file:
//
//   node split.mjs                                  # rewrite batches/ from dicts.json
//   node apply-update.mjs updates/0.1.6-alpha.1.json
//
// A key in a batch with neither a carried translation nor an entry in the update file
// is reported and fails the run: shipping a raw key is worse than not shipping.
import fs from 'node:fs'
import path from 'node:path'

const DIR = import.meta.dirname
const updateFile = process.argv[2]
if (!updateFile) {
  console.error('usage: node apply-update.mjs <updates/version.json>')
  process.exit(2)
}

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'))
const IT_DIR = path.join(DIR, 'it')
const BATCH_DIR = path.join(DIR, 'batches')

// ── the translations already written, by namespace and key ───────────────────
const carried = new Map()
let carriedFiles = 0
for (const file of fs.readdirSync(IT_DIR).filter((name) => name.endsWith('.json')).sort()) {
  let parsed
  try { parsed = readJson(path.join(IT_DIR, file)) } catch { continue }
  if (!parsed?.namespace || !parsed?.keys) continue
  const map = carried.get(parsed.namespace) ?? new Map()
  for (const [key, value] of Object.entries(parsed.keys)) if (typeof value === 'string') map.set(key, value)
  carried.set(parsed.namespace, map)
  carriedFiles++
}
const carriedKeys = [...carried.values()].reduce((total, map) => total + map.size, 0)

// ── the update file: translations for new keys and reviewed keys ─────────────
const raw = readJson(updateFile)
const overrides = new Map()
for (const [ns, entries] of Object.entries(raw.it ?? raw)) {
  if (!entries || typeof entries !== 'object') continue
  const map = new Map()
  for (const [key, value] of Object.entries(entries)) if (typeof value === 'string') map.set(key, value)
  overrides.set(ns, map)
}
const overrideKeys = [...overrides.values()].reduce((total, map) => total + map.size, 0)

// ── rewrite every batch's Italian file ──────────────────────────────────────
const batches = fs.readdirSync(BATCH_DIR).filter((name) => name.endsWith('.json')).sort()
const used = new Set()
const usedOverrides = new Set()
const missing = []
let written = 0
let fromCarry = 0
let fromUpdate = 0

for (const file of batches) {
  const source = readJson(path.join(BATCH_DIR, file))
  const keys = {}
  for (const key of Object.keys(source.keys)) {
    const override = overrides.get(source.namespace)?.get(key)
    if (override !== undefined) {
      keys[key] = override
      fromUpdate++
      used.add(`${source.namespace}\u0000${key}`)
      usedOverrides.add(`${source.namespace}\u0000${key}`)
      continue
    }
    const carry = carried.get(source.namespace)?.get(key)
    if (carry !== undefined) { keys[key] = carry; fromCarry++; used.add(`${source.namespace}\u0000${key}`); continue }
    missing.push(`${source.namespace}.${key}`)
  }
  fs.writeFileSync(
    path.join(IT_DIR, file),
    JSON.stringify({ batch: source.batch, namespace: source.namespace, total: Object.keys(keys).length, keys }, null, 1),
  )
  written++
}

// An entry that matches no key in any batch is a typo or a key that moved: it would
// otherwise be dropped in silence, and that key would ship in English.
const unusedOverrides = []
for (const [ns, map] of overrides) for (const key of map.keys()) if (!usedOverrides.has(`${ns}\u0000${key}`)) unusedOverrides.push(`${ns}.${key}`)

// Translations with no counterpart any more: the release dropped those keys.
const dropped = []
for (const [ns, map] of carried) for (const key of map.keys()) if (!used.has(`${ns}\u0000${key}`)) dropped.push(`${ns}.${key}`)

console.log(`batches rewritten: ${written}   files read: ${carriedFiles}   translations carried: ${carriedKeys}`)
console.log(`keys carried onto the new batches: ${fromCarry}`)
console.log(`keys taken from ${path.basename(updateFile)}: ${fromUpdate}  (of ${overrideKeys} in the file)`)
console.log(`keys still untranslated: ${missing.length}`)
for (const key of missing) console.log('  ! ' + key)
console.log(`entries in the update file that match no key anywhere: ${unusedOverrides.length}`)
for (const key of unusedOverrides) console.log('  ? ' + key)
console.log(`translations dropped because the release removed the key: ${dropped.length}`)
for (const key of dropped) console.log('  - ' + key)

if (missing.length > 0 || unusedOverrides.length > 0) process.exit(1)
